//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Couleur_Module
    {
        public long idCouleur_Module { get; set; }
        public Nullable<long> idModule { get; set; }
        public Nullable<long> idCouleur { get; set; }
        public Nullable<long> idModule_Maison { get; set; }
    
        public virtual Couleur Couleur { get; set; }
        public virtual Module Module { get; set; }
        public virtual Module_Maison Module_Maison { get; set; }
    }
}
