//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Couleur_Module
    {
        public long idCouleur_Module { get; set; }
        public Nullable<long> idModule { get; set; }
        public Nullable<long> idCouleur { get; set; }
        public Nullable<long> idModule_Maison { get; set; }
    
        public virtual Couleur Couleur { get; set; }
        public virtual Module Module { get; set; }
        public virtual Module_Maison Module_Maison { get; set; }
    }
}
