//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empreinte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empreinte()
        {
            this.Maison = new HashSet<Maison>();
            this.ZoneMorte1 = new HashSet<ZoneMorte>();
        }
    
        public long idEmpreinte { get; set; }
        public string nom { get; set; }
        public Nullable<double> longueur { get; set; }
        public Nullable<double> largeur { get; set; }
        public Nullable<long> idZoneMorte { get; set; }
    
        public virtual ZoneMorte ZoneMorte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maison> Maison { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZoneMorte> ZoneMorte1 { get; set; }
    }
}
