//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empreinte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empreinte()
        {
            this.Maison = new HashSet<Maison>();
        }
    
        public long idEmpreinte { get; set; }
        public string nom { get; set; }
        public Nullable<double> longueur { get; set; }
        public Nullable<double> largeur { get; set; }
        public Nullable<long> idZoneMorte { get; set; }
    
        public virtual ZoneMorte ZoneMorte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maison> Maison { get; set; }
    }
}
