
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Madera.Model
{

using System;
    using System.Collections.Generic;
    
public partial class EtatCommande
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EtatCommande()
    {

        this.Projet_EtatCommande = new HashSet<Projet_EtatCommande>();

    }


    public long idEtatCommande { get; set; }

    public string nom { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Projet_EtatCommande> Projet_EtatCommande { get; set; }

}

}
