
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Madera.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Favori
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Favori()
    {

        this.Module_Favori = new HashSet<Module_Favori>();

    }


    public long idFavori { get; set; }

    public string nom { get; set; }

    public Nullable<double> tailleSlot { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Module_Favori> Module_Favori { get; set; }

}

}
