//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maison_TypeDalle
    {
        public Nullable<double> historiquePrixM2 { get; set; }
        public long idMaison { get; set; }
        public long idTypeDalle { get; set; }
    
        public virtual Maison Maison { get; set; }
        public virtual TypeDalle TypeDalle { get; set; }
    }
}
