
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Madera.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Maison_TypeDalle
{

    public Nullable<double> historiquePrixM2 { get; set; }

    public long idMaison { get; set; }

    public long idTypeDalle { get; set; }



    public virtual Maison Maison { get; set; }

    public virtual TypeDalle TypeDalle { get; set; }

}

}
