//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module_Favori
    {
        public Nullable<double> distanceSol { get; set; }
        public Nullable<long> numSlot { get; set; }
        public long idModule { get; set; }
        public long idFavori { get; set; }
    
        public virtual Favori Favori { get; set; }
        public virtual Module Module { get; set; }
    }
}
