//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module_Maison
    {
        public Nullable<long> posXDebut { get; set; }
        public Nullable<long> posYDebut { get; set; }
        public Nullable<long> posXFin { get; set; }
        public Nullable<long> posYFin { get; set; }
        public Nullable<double> distanceSol { get; set; }
        public Nullable<double> historiquePrixModule { get; set; }
        public Nullable<double> historiquePrixCouleur { get; set; }
        public Nullable<double> historiquePrixFinition { get; set; }
        public long idModule { get; set; }
        public long idMaison { get; set; }
        public long idModule_maison { get; set; }
    
        public virtual Maison Maison { get; set; }
        public virtual Module Module { get; set; }
    }
}
