//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module_Maison
    {
        public Nullable<long> posXDebut { get; set; }
        public Nullable<long> posYDebut { get; set; }
        public Nullable<long> posXFin { get; set; }
        public Nullable<long> posYFin { get; set; }
        public Nullable<double> distanceSol { get; set; }
        public Nullable<double> historiquePrixModule { get; set; }
        public Nullable<double> historiquePrixCouleur { get; set; }
        public Nullable<double> historiquePrixFinition { get; set; }
        public long idModule { get; set; }
        public long idMaison { get; set; }
        public long idModule_maison { get; set; }
        public long idCouleur { get; set; }
    
        public virtual Maison Maison { get; set; }
        public virtual Module Module { get; set; }
        public virtual Couleur Couleur { get; set; }
    }
}
