//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.Module_Favori = new HashSet<Module_Favori>();
            this.Module_Maison = new HashSet<Module_Maison>();
        }
    
        public long idModule { get; set; }
        public string nom { get; set; }
        public Nullable<long> hauteur { get; set; }
        public Nullable<long> largeur { get; set; }
        public Nullable<double> prix { get; set; }
        public Nullable<long> idGamme { get; set; }
        public Nullable<long> idCouleur { get; set; }
        public Nullable<long> idType { get; set; }
        public Nullable<long> imgUrl { get; set; }
    
        public virtual Couleur Couleur { get; set; }
        public virtual Gamme Gamme { get; set; }
        public virtual TypeModule TypeModule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Module_Favori> Module_Favori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Module_Maison> Module_Maison { get; set; }
    }
}
