//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet_EtatCommande
    {
        public Nullable<double> prix { get; set; }
        public Nullable<long> paiementValide { get; set; }
        public long idProjet { get; set; }
        public long idEtatCommande { get; set; }
    
        public virtual EtatCommande EtatCommande { get; set; }
        public virtual Projet Projet { get; set; }
    }
}
