//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet_EtatCommande
    {
        public Nullable<decimal> dates { get; set; }
        public Nullable<double> prix { get; set; }
        public Nullable<long> paiementValide { get; set; }
        public long idProjet { get; set; }
        public long idEtatCommande { get; set; }
    
        public virtual EtatCommande EtatCommande { get; set; }
        public virtual Projet Projet { get; set; }
    }
}
