//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projet()
        {
            this.Projet_EtatCommande = new HashSet<Projet_EtatCommande>();
            this.Commercial = new HashSet<Commercial>();
        }
    
        public long idProjet { get; set; }
        public Nullable<long> devisSynchro { get; set; }
        public string nom { get; set; }
        public Nullable<double> prixFabrication { get; set; }
        public Nullable<double> prixComposant { get; set; }
        public Nullable<double> prixInstallation { get; set; }
        public Nullable<double> prixFinal { get; set; }
        public Nullable<double> reductionMarge { get; set; }
        public string numDevis { get; set; }
        public string numFacture { get; set; }
        public string numOF { get; set; }
        public string numOM { get; set; }
        public Nullable<long> kitMonte { get; set; }
        public Nullable<long> idMaison { get; set; }
        public Nullable<long> idClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Maison Maison { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projet_EtatCommande> Projet_EtatCommande { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commercial> Commercial { get; set; }
    }
}
