//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madera.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneMorte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZoneMorte()
        {
            this.Empreinte = new HashSet<Empreinte>();
        }
    
        public long idZoneMorte { get; set; }
        public Nullable<long> longueur { get; set; }
        public Nullable<long> largeur { get; set; }
        public Nullable<long> coordonneeX { get; set; }
        public Nullable<long> coordonneeY { get; set; }
        public Nullable<long> idEmpreinte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empreinte> Empreinte { get; set; }
        public virtual Empreinte Empreinte1 { get; set; }
    }
}
